### ISSUE TITLE
neo4j container hangs up after 1 week with driver failed programming external connectivit

### ISSUE THREAD

**Issue by antoniodimariano** [docker/docker.github.io#10500]
### Problem description
I have the following configuration for running neo4j 3.5 

```
neo4j:
    image : "neo4j:3.5"
    restart: "no"
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/conf:/conf
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/import:/import
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/plugins:/plugins
    environment:
      #Raise memory limit
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
```

The container runs just fine for more or less a week, then the service stops responding. No connection on the http port 7474, no internal connection on the 7687. 
Tried to stop the container, no result. 
Tried to restart the container, no result. 
I managed to remove --force. When I do a docker-compose up -d I got this error 

```
 ERROR: for xxx_neo4j_1  Cannot start service neo4j: driver failed programming external connectivity on endpoint xxx_neo4j_1 (b57fee22143eae2882838623a9e5f995f5576ed9f5d495ba1c03233ab295e608): Bind for 0.0.0.0:7687 failed: port is already allocated

```

From a `sudo lsof -i -P -n | grep LISTEN` I saw 

```
docker-pr 25811      root    4u  IPv6 25486670      0t0  TCP *:7687 (LISTEN)
docker-pr 25822      root    4u  IPv6 25486701      0t0  TCP *:7474 (LISTEN)
```

I killed -9 those pid but the error the connectivity error was still there. 

At the moment the only fix I've found is to restart docker. After a clean restart, the neo4j container runs fine. 

### Project version(s) affected

* Docker version 17.05.0-ce, build 89658be
* neo4j:3.5
* ubuntu 13.10 
* 2GB RAM
* 50GB Storage

### Suggestions for a fix

`sudo service docker restart`
