### ISSUE TITLE
Update page with example that uses an external secret file

### ISSUE THREAD

**Issue by rupakg** [docker/docker.github.io#10584]
File: [ee/ucp/interlock/usage/tls.md](https://docs.docker.com/ee/ucp/interlock/usage/tls/)

I want to add this additional section that shows how the compose file labels change based on the name of the secret since the secrets are created externally.

After the line:

`docker stack deploy --compose-file docker-compose.yml demo`

Please add the following section:

====================================================================
The compose file has:

```
com.docker.lb.ssl_cert: demo_app.example.org.cert
com.docker.lb.ssl_key: demo_app.example.org.key
```

The secrets are referenced as such:

```
secrets:
  app.example.org.cert:
    file: ./app.example.org.cert
  app.example.org.key:
    file: ./app.example.org.key
```

The docker stack was created with a name `demo`

Therefore the secret that is created as part of the stack creation will have the stack name **prefixed** to the name of the secret in the compose file i.e. `demo_app.example.org.cert`
So this example works fine.

But if the secrets were created externally like so:

```
secrets:
  app.example.org.cert:
    external: true
  app.example.org.key:
    external: true
```

Note that the secret name will **NOT be prefixed** with the stack name as in the earlier example but will still be named `app.example.org.cert`

And, so the compose file labels for cert and key will change to:

```
com.docker.lb.ssl_cert: app.example.org.cert
com.docker.lb.ssl_key: app.example.org.key
```
====================================================================
