### ISSUE TITLE
The example you use on this page does not do what the docs say it does

### ISSUE THREAD

**Issue by hogansch** [docker/docker.github.io#10749]
File: [compose/startup-order.md](https://docs.docker.com/compose/startup-order/)

Using the sample docker-compose.yml in the documentation,

```
version: "2"
services:
  web:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
  db:
    image: postgres
```

`docker-compose up` starts the web service first. Changing the order of the services makes no difference. I'm aware that there's a difference between when a service is started versus when it is ready. the db does not _start_ before the web service even using the sample code in the documentation. Notice that the down vote ratio is 700+ to up vote 150+ for this documentation.

Best I can tell, if a docker-compose service refers to a Dockerfile to build, it is started first no matter how you order them or whether you use `depends_on` though I see no explanation of this anywhere in the documentation.
