### ISSUE TITLE
Feature Request dockerfile allow base image from github repository

### ISSUE THREAD

**Issue by CarlosOnline** [docker/docker.github.io#10879]
Docker compose allows building an image from a github repository.

_Unfortunately I can't do the same from a dockerfile._

As a result I need to use docker-compose instead to first build the **remote_service**, which I can then consume in the Dockerfile.

REQUEST: **Allow DockerFile FROM to source to a github repository**, similar to what is available in docker-compose.

**dockery-compose.yml**
```
services:
  remote_service:
    build:
      context: https://github.com/user/repo.git
    image: remote:v1

  myproject_multi_stage_build:
    build:
      context: .
```

**Dockerfile**
```
FROM remote_service
...
```
