### ISSUE TITLE
Kubernetes deployment fails to complete

### ISSUE THREAD

**Issue by michael-mml** [docker/docker.github.io#11639]
File: [get-started/kube-deploy.md](https://docs.docker.com/get-started/kube-deploy/)

Using the `bulletinboard:1.0` image, after step 1: `kubectl apply -f bb.yaml`, the deployment fails to complete.

Running `kubectl logs --selector='bb=web'` shows:
```bash
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-27T05_08_40_200Z-debug.log
```
and I've verified that the [`package.json`](https://github.com/dockersamples/node-bulletin-board/blob/master/bulletin-board-app/package.json) in the `bulletinboard` image does not define `start` as a script.

Sort of relates to: https://github.com/docker/docker.github.io/issues/11628

**Comment by gurpartb** [comment]
Seems like you are suppose to do this step first: https://docs.docker.com/get-started/02_our_app/

Or you can use this modified bb.yaml instead
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: docker/getting-started
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
```
