### ISSUE TITLE
.yml errors + small spelling mistake

### ISSUE THREAD

**Issue by BHillenbrand722** [docker/docker.github.io#11653]
File: [get-started/nodejs/develop.md](https://docs.docker.com/get-started/nodejs/develop/)

The guide tells you to create a docker-compose yaml file with the following contents: 

```yaml
version: '3.8'

services:
 notes:
   build:
     context: .
   ports:
     - 8080:8080
     - 9229:9229
   environment:
     - SERVER_PORT=8080
     - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/notes
   volumes:
     - ./:/code
   command: npm run debug

 mongo:
   image: mongo:4.2.8
   ports:
     - 27017:27017
   volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
 volumes:
   mongodb:
   mongodb_config:
```

Upon trying to run this file as the guide states you get an error `"Unsupported config option for services.volumes: 'mongodb'"`. Further inspection indicates that this error is due to the indentation difference between the final "volumes:" and "mongodb:" along with "mongodb_config:". (Fixing mongodb and rerunning gives the same error for mongodb_config). However, fixing this error results in another error; `"The Compose file is invalid because: Service volumes has neither an image nor a build context specified. At least one must be provided."` This error is more straight forward but given that this is straight from the Docker guide it is not rectifiable given the learners knowledge. 

Also below the next chunk of code is written, "If all goes will..." which should be "If all goes well...".
