### ISSUE TITLE
ECS Container Resources - Bad Example, should be cpus not cpu

### ISSUE THREAD

**Issue by brendonparker** [docker/docker.github.io#12256]
File: [cloud/ecs-compose-features.md](https://docs.docker.com/cloud/ecs-compose-features/)

The example at the bottom of the page, "Container Resources" has an invalid attribute:

```
services:
    nginx:
        image: mycompany/webapp
        deploy:
          resources:
            limits:
              cpu: 0.5
              memory: 2Gb
```

`cpu` isn't valid, should be `cpus`, and must be a string value. So:

```
services:
    nginx:
        image: mycompany/webapp
        deploy:
          resources:
            limits:
              cpus: "0.5"
              memory: 2Gb
```

Without this change, when you try and use this sample, you'll get:

> .deploy.resources.limits Additional property cpu is not allowed

_putting that here for search-engine :)_
