### ISSUE TITLE
Compose: Variable Substitution in Ports declaration

### ISSUE THREAD

**Issue by darylf** [docker/docker.github.io#12596]
### Problem description

I would like to provide a default value in `docker-compose.yml` for environment variables, when an environment variable isn't set. I found [a thread](https://github.com/docker/docker.github.io/issues/6914) which references using variable substituion for the [environment section](https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution), but is it possible to also use this concept in other features, such as port declarations?

e.g:
```
  proxy:
    build: ./proxy
    ports:
      - ${PROXY_PORT:80}:80
      - ${PROXY_PORT_SSL:443}:443
```

If I try this, I get the error:
`ERROR: Invalid interpolation format for "ports" option in service "proxy": "${PROXY_PORT:80}:80"`

### Problem location

I'm not sure if this is a documentation issue, or if it isn't implemented. Please advise.
