### ISSUE TITLE
Release notes 1.29 - initContainer information missing

### ISSUE THREAD

**Issue by dennzo** [docker/docker.github.io#12633]
### Problem description

In the version 1.29 the support for initContainers have been added through the following PR.    
https://github.com/docker/compose/pull/8122

But there is no reference to this feature in the release notes. Also there is no documentation provided on how to use this.    
https://github.com/docker/docker.github.io/blob/master/compose/release-notes.md#1290

### Problem location

I saw a problem on the following URLs: 
- https://docs.docker.com/compose/release-notes/
- https://docs.docker.com/compose/compose-file/compose-file-v3/

### Project version(s) affected
docker-compose - 1.29

### Suggestions for a fix
Add the information to the release notes and also add some context on how to use it to the main documentation of docker-compose.

Thanks very much! :)

**Comment by carehart** [comment]
Seeking clarification on this also. The listed release notes refers to "Add a `depends_on` condition to wait for successful service completion". Other resources discussing the addition of init containers (like [the PR](https://github.com/compose-spec/compose-spec/pull/134) and [discussions for it](https://github.com/docker/compose/issues/6855)) don't indicate that. 

Is this feature enabled by the `init: true` (for `services`), indicated in the [compose file doc](https://docs.docker.com/compose/compose-file/compose-file-v3/#init), indicating that was added in 3.7? 

To be clear, I'm not an active participant in things. I just heard the news (of init containers in Compose). Apologies if I have something crazy wrong here.

**Comment by aritas1** [comment]
`depends_on` has a `condition` key.  the following values are available according to the [compose tests](https://github.com/ojab/compose/blob/4daad056c4d54ea5d4e84f097f9b825067fa016d/tests/unit/config/config_test.py#L2421).
`service_started` `service_healthy` `service_completed_successfully`

you can try this with my example.
```
version: '3.4'
services:
  my_init:
    image: alpine
    command: /bin/sh -c "exit 1"
  my_follower:
    depends_on:
      my_init:
        condition: service_completed_successfully
    image: alpine
    command: /bin/sh -c "echo init finished"
```
if the depends_on container exits none zero, you will see an error:
```
Creating my_init_1 ... done

ERROR: for my_follower  Container "cd06a63129c2" exited with code 1.
ERROR: Encountered errors while bringing up the project.
```

**Comment by carehart** [comment]
I appreciate that as a seeming clue. Still looking forward to more official confirmation/documentation (for everyone's sake, I mean). I'm on mobile as I see this so am challenged to dig around based on this info, but I wanted to reply before losing track of my notification of your reply. Perhaps someone else may have additional thoughts.

**Comment by shoce** [comment]
> Is this feature enabled by the `init: true` (for `services`), indicated in the [compose file doc](https://docs.docker.com/compose/compose-file/compose-file-v3/#init), indicating that was added in 3.7?

No `init: true` is to "Run an init inside the container that forwards signals and reaps processes." according to the docs. So, absolutely different feature.

**Comment by shoce** [comment]
> `depends_on` has a `condition` key. the following values are available according to the [compose tests](https://github.com/ojab/compose/blob/4daad056c4d54ea5d4e84f097f9b825067fa016d/tests/unit/config/config_test.py#L2421).
> `service_started` `service_healthy` `service_completed_successfully`

Yes, i confirm that works. Below config starts `testback` only after `testback_prepare` finishes successfully. 

```
version: '3.7'
services:
    testback_prepare:
        container_name: testback_prepare
        image: alpine
        command: /bin/sh -c 'echo come on; sleep 3'
    testback:
        container_name: testback
        image: alpine
        command: /bin/sh -c 'echo yohoho; sleep 1000'
        depends_on:
            testback_prepare:
                condition: service_completed_successfully
```

```
docker-compose --version
docker-compose version 1.29.1, build c34c88b2
```

**Comment by carehart** [comment]
OK, it seems to be specifically that the depends_on value of service_completed_successfully is what's new in docker-compose 1.29.0, which is what gives the equivalent of initcontainer functionality in compose: that a given container/service must not only start but complete (and complete successfully) before the dependent container/service will proceed to start.

Back to the initial discussion in this thread, it was just not as clear in the resources I or we (?) were looking at. Thanks.

**Comment by bluebrown** [comment]
I seems like it's not waiting for completion.

This yaml file

```yaml
services:
  init:
    image: busybox
    command: sh -c 'echo "$$(date +%H:%M:%S) running migration..."; sleep 20; echo "$$(date +%H:%M:%S) migration completed"'
  app:
    image: node:alpine
    command: node -e 'console.log(new Date().toLocaleTimeString(), "app started")'
    depends_on:
      init:
        condition: service_completed_successfully
```

Produces the below output. So it seems like the app is started before the init container even starts.

```bash
$ docker container prune -f
$ docker compose up
[+] Running 2/2
 ⠿ Container test_init_1  Started                                                                                                                                                                                                1.3s
 ⠿ Container test_app_1   Started                                                                                                                                                                                               22.7s
Attaching to app_1, init_1
app_1   | 12:04:11 PM app started
app_1 exited with code 0
init_1  | 12:04:12 running migration...
init_1  | 12:04:32 migration completed
init_1 exited with code 0
```

Strange enough when I am using this file 

```yaml
services:
  init:
    image: busybox
    command: sh -c 'echo "$$(date +%H:%M:%S) running migration..."; sleep 20; echo "$$(date +%H:%M:%S) migration completed"'
  app:
    image: busybox
    command: sh -c 'echo "$$(date +%H:%M:%S) app started"'
    depends_on:
      init:
        condition: service_completed_successfully
```

It behaves as expected.

```
$ docker container prune -f
$ docker compose up
[+] Running 2/2
 ⠿ Container test_init_1  Started                                                                                                                                                                                                1.3s
 ⠿ Container test_app_1   Started                                                                                                                                                                                               22.6s
Attaching to app_1, init_1
init_1  | 12:07:12 running migration...
init_1  | 12:07:32 migration completed
init_1 exited with code 0
app_1   | 12:07:34 app started
app_1 exited with code 0
```

Am I missing something?
