### ISSUE TITLE
Problem : Portainer - not declaration was found in volumes section.

### ISSUE THREAD

**Issue by dexter74** [docker/docker.github.io#12972]
### Problem description
**ERROR:** Name volume Video:/mnt/Video is used in service "Plex" but not declaration was found in volumes section.

### Problem location
None

### Project version(s) affected
Docker version 20.10.7, build f0df350
docker-compose version 1.27.4, build 40524192

### Description Problem
- Installation of Docker, Docker-compose > OK
- Modifying the /lib/systemd/system/docker.service service
```
ExecStart=/usr/bin/dockerd --data-root /mnt/docker -H fd:// --containerd=/run/containerd/containerd.sock
```
- Reload / Restart service:
```
systemctl daemon-reload ;
systemctl restart docker* ;
systemctl status docker* ;
```
- Installation of Portainer-ce (Release: 2.5.1)
- Creating a Video Volume (CIFS)
- Creation of the stack

**Volume Video**
```
docker volume create --driver local \
        --opt type=cifs \
        --opt device=//192.168.1.2/Video \
        --opt o=username=XXXX,password=XXXX,vers=3.0,file_mode=0777,dir_mode=0777 \
        --name Video
```

**Docker-compose.yml:**
```
version: '3.9'
services:
  Plex:
    image: 'linuxserver/plex'
    container_name: 'CN_Plex'
    network_mode: 'bridge'
    restart: 'always'
    hostname: 'Plex'
    domainname: 'labs'
    environment:
      PUID: '1000'
      PGID: '100'
      TZ: 'Europe/Paris'
      PLEX_CLAIM: 'XXXXXXXXX'
      VERSION: 'docker'
    ports:
      - '1001:32400'    # WebUI
    volumes:
      - 'Video:/mnt/Video'
    labels:
      cacher: 'non'
```
