### ISSUE TITLE
help docker-compose push An image does not exist locally with the

### ISSUE THREAD

**Issue by duolabmeng6** [docker/docker.github.io#13093]
File: [compose/reference/push.md](https://docs.docker.com/compose/reference/push/)

```
version: "3"
services:
  php8:
    build: ./services/php
    image: duolabmeng666/php8-nginx

```
```
docker-compose push
```
```
The push refers to repository [docker.io/duolabmeng666/php8-nginx]
ERROR: An image does not exist locally with the tag: duolabmeng666/php8-nginx
```

How to solve this problem?
