### ISSUE TITLE
Explain order of precedence between ENV-FILE and ENV in compose files

### ISSUE THREAD

**Issue by VeeeneX** [docker/docker.github.io#1312]
I've been reading docs and I noticed one cool feature and It's environment order

ENV file:
```env
VAR=1
```
docker-compose.yml
```yaml
version: "2"
services:
  test:
    image: busybox
    command: env
    env_file:
     - ./test
    environment:
     - INVAR=1
```
Output:
```
Starting dockercomposeexample_test_1
Attaching to dockercomposeexample_test_1
test_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
test_1  | HOSTNAME=f843386961b3
test_1  | VAR=1
test_1  | INVAR=1
test_1  | HOME=/root
dockercomposeexample_test_1 exited with code 0
```
And with default env

docker-compose.yml
```yaml
version: "2"
services:
  test:
    image: busybox
    command: env
    env_file:
     - ./test
    environment:
     - VAR=1
```
Output:
```
Starting dockercomposeexample_test_1
Attaching to dockercomposeexample_test_1
test_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
test_1  | HOSTNAME=f843386961b3
test_1  | VAR=1
test_1  | HOME=/root
dockercomposeexample_test_1 exited with code 0
```

File: [compose/environment-variables.md](https://docs.docker.com/compose/environment-variables/)
