### ISSUE TITLE
Example of depends_on usage required

### ISSUE THREAD

**Issue by flyte** [docker/docker.github.io#13516]
File: [docker-hub/builds/automated-testing.md](https://docs.docker.com/docker-hub/builds/automated-testing/)

It's unclear how to actually use the `depends_on` feature described in this automated-testing documentation.

If I add some services and a `depends_on` to `sut` then I get:

```
The Compose file './docker-compose-test.yml' is invalid because:
Unsupported config option for sut: 'depends_on'
building docker-compose-test.yml (1)
```

using the following `docker-compose-test.yml` file:

```yaml
sut:
  build: .
  command: ./run_tests.sh
  depends_on:
    - db
db:
  image: postgis/postgis:12-3.1-alpine
  environment:
    POSTGRES_PASSWORD: pgpassword
  expose:
    - "5432"
```

**Comment by flyte** [comment]
I've managed to work it out by using a versioned docker-compose file:

```yaml
version: "3.9"

services:
  sut:
    build: .
    command: ./run_tests.sh
    depends_on:
      - db
  db:
    image: postgis/postgis:12-3.1-alpine
    environment:
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432/tcp"
```

but bonus points if you can explain how to find the randomly assigned port for `db` from `run_tests.sh`?!
