### ISSUE TITLE
Clarification needed in "Fluentd logging driver" documentation

### ISSUE THREAD

**Issue by qmonitoring** [docker/docker.github.io#13835]
File: [config/containers/logging/fluentd.md](https://docs.docker.com/config/containers/logging/fluentd/)

Option _fluentd-async_ should be changed to _fluentd-async-connect_ in the documentation text.

**Comment by thaJeztah** [comment]
Was there a problem you ran into?
The `fluentd-asyc-connect` option was deprecated in favor of `fluent-async`; see https://github.com/moby/moby/pull/39086

**Comment by qmonitoring** [comment]
Docker version: 20.10.6
Docker compose version:  '3.8'

Worked config snippet :

```
        logging:
            driver: fluentd
            options:
                fluentd-async-connect: "true"
```

if I use this one:

```
        logging:
            driver: fluentd
            options:
                fluentd-async: "true"
```
the error is:
_Error response from daemon: unknown log opt 'fluentd-async' for fluentd log driver_
