### ISSUE TITLE
Incorrect Configuration for django+postgresql yml file

### ISSUE THREAD

**Issue by andrewp24** [docker/docker.github.io#14021]
The guide currently specifies that only the web environment contains the POSTGRES_NAME, USER, and PASSWORD information.

This should also be in the db service section. 

the file should look like the following, otherwise the database will not be able to start and then the web server will not be able to connect to the db.

```
version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
```

(step 9 in "Quickstart: Compose and Django" section)
File: [samples/django.md](https://docs.docker.com/samples/django/)
