### ISSUE TITLE
Remove "true" from external: in "networks: stanza?  

### ISSUE THREAD

**Issue by pablollama** [docker/docker.github.io#14084]
File: [compose/networking.md](https://docs.docker.com/compose/networking/)

Heya, should services:
```
 services:
  # ...
networks:
  default:
    external: true
    name: my-pre-existing-network
```
have the "true" removed? 

Thanks, 
Paul
