### ISSUE TITLE
[Java docs feedback]

### ISSUE THREAD

**Issue by javaLux** [docker/docker.github.io#15646]
### Bad docker compose file

I found a bug in the docker compose file instructions from the language specific Java guide.
If I build and run the file as shown, I get a JDBC SQL Exception. Because the user 'petclinic' does not exist yet.

### Problem location
The problem is on the currently docker-compose file instructions on the Language-specific-guides for Java  (see also https://docs.docker.com/language/java/develop/)

`version: '3.8'
services:
 petclinic:
   build:
     context: .
     target: development
   ports:
     - 8000:8000
     - 8080:8080
   environment:
     - SERVER_PORT=8080
     - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
   volumes:
     - ./:/app

 mysqlserver:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
    mysql_data:
    mysql_config:
`

### Project version(s) affected
Im using the following Frameworks:

- Docker-Desktop 4.11.1
- Docker-Engine 20.10.18 (Community)

OS / Arch:
- Linux (Ubuntu LTS 22.04) / amd64

### Suggestions for a fix
I fix my docker compose file in this way:

`
version: '3.8'

volumes:
    mysql_data:
    mysql_config:

services:
 mysqlserver:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

 petclinic:
   build:
     context: .
     target: development
   ports:
     - 8000:8000
     - 8080:8080
   environment:
     - SERVER_PORT=8080
     - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
   volumes:
     - ./:/app
`

**Comment by craig-osterhout** [comment]
Hi @javaLux, thank you for raising the issue.

It looks like `depends_on` is missing.
The following should also fix the issue.

```
services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile-multi
      target: development
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
    
  mysqlserver:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config
```
