### ISSUE TITLE
Docker-compose file for  node-docker application tutorial. 

### ISSUE THREAD

**Issue by mudabir94** [docker/docker.github.io#15681]
File: [language/nodejs/develop.md](https://docs.docker.com/language/nodejs/develop/)

Hi, In the language specific guide for Node and in section "develop your app", docker-compose.dev.yml is created. 
Is it possible to add the code for a docker-compose.yml file as well, which can be used for deployment later. 

Thank you.

**Comment by craig-osterhout** [comment]
Hi @mudabir94, thanks for sharing the feedback.
Please check the following topic to learn about how to prepare a Compose file for production, https://docs.docker.com/compose/production/

If you want to use Swarm, please see https://docs.docker.com/get-started/swarm-deploy/

For example, remove the app volume override and the command override from the compose file.
You'd probably also want your production server to pull the node-docker image from a registry (like Docker Hub) rather than building it on the production machine.

```
version: '3.8'

services:
 notes:
  image: your-dockerid/node-docker
  ports:
   - 8000:8000
   - 9229:9229
  environment:
   - SERVER_PORT=8000
   - CONNECTIONSTRING=mongodb://mongo:27017/notes
   
 mongo:
  image: mongo:4.2.8
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
volumes:
 mongodb:
 mongodb_config:
```

To get more help, please try the Docker Community Slack, 
https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA
