### ISSUE TITLE
 localhost:30001 doesn't work as suggested by tutorial

### ISSUE THREAD

**Issue by TheOnlyWei** [docker/docker.github.io#15749]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

I cloned the getting-started repository. I followed tutorial to the step 3 of following tutorial:
https://docs.docker.com/get-started/kube-deploy/#deploy-and-check-your-application

There you need to enter localhost:30001 to get the bulletin board but it doesn't work. I can get the board from localhost:3000 but not localhost:30001. On localhost:30001, I get empty response or connection reset error.

I am using windows 11 with Docker Desktop.

**Comment by craig-osterhout** [comment]
Hi @TheOnlyWei, thanks for sharing the issue. Please replace the contents of your bb.yaml file with the contents below and let us know if it works.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: docker/getting-started
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
```

**Comment by TheOnlyWei** [comment]
Hi @craig-osterhout, still not working for me. I had to change nodePort to 30002 because for some reason localhost:30001 is suddenly routing me to localhost:30001/tutorials of docker getting started page after applying your YAML code.

![Screenshot 2022-09-27 123018](https://user-images.githubusercontent.com/19400755/192618441-5e7f61c2-7b7e-4979-a5c0-5516abc8ec5e.jpg)

Does the YAML code work on your machine? It should bring up the bulletin board web-app.

**Comment by craig-osterhout** [comment]
Hi @TheOnlyWei, thanks for trying that. Sorry, I should've added more context. I was just verifying it is an issue in the yaml and not an environment/image issue before looking more deeply at it. 
The reason you saw the guide is that the yaml from above was pulling the `docker/getting-started` image from Docker Hub. It's not the same as the Todo app, although it's named "getting-started" also. 

As for the original issue, it looks like the yaml in the guide is missing ` imagePullPolicy: Never`.
I'll update the guide to include this. Thanks again for following up.


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: getting-started
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    ```
