### ISSUE TITLE
confusion about depends_on and version keys in compose file

### ISSUE THREAD

**Issue by czka** [docker/docker.github.io#1622]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

This is about docker-compose 1.11.1. I'm confused about the `depends_on` with `condition` in version 3 format.

Version 3 doc advertises it (https://docs.docker.com/compose/compose-file/#dependson), whereas docker-compose 1.10.0 release notes (https://github.com/docker/compose/releases/tag/1.10.0) state that "This feature **will not be ported to version 3** Compose files".

The latter seems to be true, as the following compose fails with version 3 as follows:

```
version: '3'
services:

  service1:
    build: .
    container_name: one
    entrypoint: ["echo", "one complete!"]
    depends_on:
      service2:
        condition: service_healthy

  service2:
    build: .
    container_name: two
    entrypoint: ["sh", "-c", "sleep 5 && nc -l 5559"]
    healthcheck:
      test: "echo 'bababa' | nc localhost 5559"
      interval: 3s
      retries: 3
```

```
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.service1.depends_on contains an invalid type, it should be an array
```

Trying to fix this with:

```
    depends_on:
      - service2
          condition: service_healthy
```

results in:

```
$ docker-compose up
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 10, column 20
```

Is `depends_on` supported in version 3 or not? If not, please adjust the docs as needed. Or maybe I'm just doing it wrong? An example for format 3 next to the 2.1 one would come in handy then.

FYI, the Dockerfile used in `build` is:

```
FROM centos:latest

RUN yum --quiet --assumeyes upgrade \
    && yum --quiet --assumeyes install nmap-ncat
```
