### ISSUE TITLE
NetworkingConfig documentation missing

### ISSUE THREAD

**Issue by ekkis** [docker/docker.github.io#3169]
File: [engine/api/v1.24.md](https://docs.docker.com/engine/api/v1.24/), CC @mstanleyjones 

the method for creating containers contains the JSON key "NetworkingConfig" but the documentation does not cover that at all.  I'm trying to figure out how to join a container to a network, the same as I would do in a docker-compose file by:

```
services:
  myservice:
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true
```

please help?
