### ISSUE TITLE
compose-file reference should include `credential_spec` documentation

### ISSUE THREAD

**Issue by friism** [docker/docker.github.io#3687]
I think the important file is `compose/compose-file/index.md`

Related:

 * https://github.com/moby/moby/pull/32483
 * https://github.com/docker/cli/pull/71
 * https://github.com/moby/moby/pull/32339

Here's an example:

```
version: "3.3"
services:
  test:
    image: microsoft/windowsservercore
    credential_spec:
      file: "WebApplication1.json"
    command: powershell -c Sleep 3600
    deploy:
      endpoint_mode: dns-rr
```
