### ISSUE TITLE
Constraints in Compose file should under "environment" not "labels"

### ISSUE THREAD

**Issue by twang2218** [docker/docker.github.io#382]
URL: [https://docs.docker.com/compose/swarm.md](https://docs.docker.com/compose/swarm/)

There are 2 examples

``` yaml
version: "2"
services:
  foo:
    image: foo
    volumes_from: ["bar"]
    network_mode: "service:baz"
    labels:
      - "constraint:node==node-1"
  bar:
    image: bar
    labels:
      - "constraint:node==node-1"
  baz:
    image: baz
    labels:
      - "constraint:node==node-1"
```

and 

``` yaml
# Schedule containers on a specific node
labels:
  - "constraint:node==node-1"

# Schedule containers on a node that has the 'storage' label set to 'ssd'
labels:
  - "constraint:storage==ssd"

# Schedule containers where the 'redis' image is already pulled
labels:
  - "affinity:image==redis"
```

I think both of them are wrong, the `constraint` should under `environment`. See the following example from https://docs.docker.com/swarm/scheduler/filter/#/example-node-constraints:

``` bash
$ docker tcp://<manager_ip:manager_port>  run -d -P -e constraint:storage==ssd --name db mysql
```
