### ISSUE TITLE
Instructions for Windows users on `docker-machine scp` Step of Getting Started

### ISSUE THREAD

**Issue by williamtdr** [docker/docker.github.io#3833]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen 

Trying to run the tutorial on Windows 10 with hyper-v, the step of uploading the compose file via SCP fails because there is no suitable SCP binary available for Windows:
`You must have a copy of the scp binary locally to use the scp feature`

Putty's pscp does not support the arguments used by the program. The solution is for Windows users to download Git Bash, run the program as administrator, go to the directory the compose file is in, and run the command again. Workaround was found from [this stackoverflow post](https://stackoverflow.com/questions/42312359/docker-machine-on-windows-10-you-must-have-a-copy-of-the-scp-binary-locally-t).

**Comment by joaofnfernandes** [comment]
Instead of providing a workaround, the tutorial should teach you how to create the files directly inside the VM. This way the commands will be agnostic to the installation.

We would ask users to `docker-machine ssh` and then copy-paste this to create a `docker-compose.yml` file inside the VM:

```
cat << 'EOL' > docker-compose.yml
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: username/repository:tag
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
EOL
```
