### ISSUE TITLE
Missing documentation for memory limits/reservations in docker-compose V3

### ISSUE THREAD

**Issue by osman-masood** [docker/docker.github.io#4636]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/), CC @mstanleyjones

How do I use any of the memory reservation/limitation functionality in docker-compose? It's missing from the docker-compose reference as well (https://docs.docker.com/compose/compose-file/#resources). All it says is that "it replaces the older resource constraint options," but doesn't say what it replaces them with or provide any examples.

I've tried doing 
```
            "resources": {
                "limits": {
                    "memory": "1g",
                    "memory-swap": "1g"
                }
            }
```
But it tells me it doesn't recognize `memory-swap`.

**Comment by mstanleyjones** [comment]
It's right there, in the same link you provided. See the code sample:

```
version: '3'
services:
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M

```

Am I missing something about your question?

cc/ @shin-
