### ISSUE TITLE
Feedback for: compose/gettingstarted.md

### ISSUE THREAD

**Issue by ubershmekel** [docker/docker.github.io#477]
URL: [https://docs.docker.com/compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

The code in the article did not work for me. I got this error on Docker 1.12.1 on Windows 10:

```
web_1    | python: can't open file 'app.py': [Errno 2] No such file or directory
```

I had to remove the volume section from the `yml` which fixed it:

```
    version: '2'
    services:
      web:
        build: .
        ports:
         - "5000:5000"
        depends_on:
         - redis
      redis:
        image: redis
```

I would also recommend supplying a zip file with the whole thing so I could have just downloaded it instead of copy pasting which introduced indentation issues in app.py.
