### ISSUE TITLE
Create compatibility YAML files

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#5189]
There are a few compatibility matrices that need to be covered:

Docker Version <---> API Version
Docker Version <---> UCP/DTR Version
Docker Version <---> Compose File Version

Structuring these in YAML would make them queryable for many other purposes. 

Example structure:

```
- release
   docker-version: 17.06
   compose:
   - version: 3
   - version: 2
   - version: 1
   ucp:
   - version: 2.0
   - version: 2.2
   ...
- release
   docker-version: ...
```
etc...

Filename suggestion: `product-metadata.yaml`
