### ISSUE TITLE
Redis volume error - invalid mount config for type

### ISSUE THREAD

**Issue by levidurfee** [docker/docker.github.io#5479]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/), CC @johndmulhausen 

I tried this a few times, but perhaps I didn't follow the tutorial correctly. I wasn't able to get Redis running until I remove the volume. Below is the `docker-compose.yml` file that finally worked for me. However, that won't persist data, right?

**docker-compose.yml**

```yml
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    # this is the docker image on docker hub
    image: levidurfee/get-started:part2
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
```

These docs are the best I've seen in a long time. I've been able to follow along easily. Thank you!

**Comment by levidurfee** [comment]
This works

## Snippet from docker-compose.yml

```yml
volumes:
      - /root/data:/data
```

## docker-compose.yml

```yml
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    # this is the docker image on docker hub
    image: levidurfee/get-started:part2
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /root/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
```
