### ISSUE TITLE
Explanation about how do non-existent host OS volumes handled by docker-compose up

### ISSUE THREAD

**Issue by BentCoder** [docker/docker.github.io#5641]
### Problem description

```
version: '3'
services:
    my_service:
        container_name: my_container
        build: ./my_build
        volumes:
            - ../host_dir:/guest_dir
```

Assume that the `host_dir` doesn't exists yet and we run `ubuntu@linux:~$ docker-compose up` command. As a result our `host_dir` will get created and have `root:root` permissions attached to it (_inc. sub-directories & files etc_).

The problem here is, some people (_inc. myself_) think/expect that the permissions would be `ubuntu:ubuntu` which is the user who executes the command.

### Problem location

The current behaviour has been explained [here](https://github.com/docker/compose/issues/5507) and the possible solution.

### Suggestions for a fix

Since I haven't seen a clear notification regarding to the expected behaviour, it would be good to say something like below:

> If you don't manually create directories (_volumes_) and grant desired permissions to them in host OS before running `docker-compose up` command, docker will automatically create directories (_volumes_) for you and assign `root:root` ownership to them.
