### ISSUE TITLE
Correct placement preferences example

### ISSUE THREAD

**Issue by oleg-fiksel** [docker/docker.github.io#5804]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01 

This should be:
```
version: '3.3'
services:
  db:
    image: postgres
    deploy:
      placement:
        constraints:
          - node.role == manager
          - engine.labels.operatingsystem == ubuntu 14.04
        preferences:
          - spread: node.labels.zone
```

Because: https://github.com/moby/moby/pull/32743
