### ISSUE TITLE
Explicitly expose 5432 port for db

### ISSUE THREAD

**Issue by benlindsay** [docker/docker.github.io#5864]
File: [compose/django.md](https://docs.docker.com/compose/django/), CC @gbarr01 

First, thanks for all the extensive documentation on docker! There's just one thing that tripped me up.

With the `docker-compose.yml` as written, `docker-compose up` was consistently failing on both my macbook and imac. I'd get an error that looks like this:
```
web_1  | psycopg2.OperationalError: could not connect to server: Connection refused
web_1  | 	Is the server running on host "db" (172.18.0.2) and accepting
web_1  | 	TCP/IP connections on port 5432?
```
I found a solution to a similar error [here](https://stackoverflow.com/a/38883539/2680824), and adding that
```
ports:
  - "5432:5432"
```
item under `db` fixed my problem. So my `docker-compose.yml` file looks like this:
```
version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
```
I don't know if that change will break anything on other systems, but it worked on mine. If there's another more general fix to this problem that would be great too. I spent about an hour trying to figure out what was going on here, and maybe other people have too.
