### ISSUE TITLE
Collect Docker metrics with Prometheus: daemon.json config

### ISSUE THREAD

**Issue by cpritcha** [docker/docker.github.io#6028]
File: [config/thirdparty/prometheus.md](https://docs.docker.com/config/thirdparty/prometheus/), CC @johndmulhausen

### Version Info

```
docker --version
Docker version 17.12.0-ce, build c97c6d6
```

Prometheus Version: prom/prometheus:v2.1.0

### Process to get Prometheus example working

I've been following along with the Prometheus metrics guide but when I set 

```json
{
  "metrics-addr" : "127.0.0.1:9323",
  "experimental" : true
}
```

 in `/etc/docker/daemon.json` and start Prometheus with the given yml file (in docker-compose) I get context limit exceeded errors for both the docker and prometheus jobs. 

If I replace 'localhost' in `prometheus.yml` with 127.0.0.1 the prometheus job works correctly but for the docker job I get an error `Get http://127.0.0.1:9323/metrics: dial tcp 127.0.0.1:9323: getsockopt: connection refused`. Here is the config

```yml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout:      15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'docker'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.

    static_configs:
      - targets: ['127.0.0.1:9323']
```

I then tried setting the docker ip address to 172.17.0.1 (my docker0 network ip) but got the same error `Get http://172.17.0.1:9323/metrics: dial tcp 172.17.0.1:9323: getsockopt: connection refused`.

After that I adjusted `daemon.json` to

```json
{
  "metrics-addr" : "0.0.0.0:9323",
  "experimental" : true
}
```

and restarted the docker service. Now I can connect to both docker metrics and prometheus metrics. 

### Request

Clarify the project setup. Should the network be set to host for this tutorial? Otherwise, if the `metrics-addr` in `daemon.json` should be localhost how do I connect to it from within the container?
