### ISSUE TITLE
I can mirror my private registry, is docmentation wrong?

### ISSUE THREAD

**Issue by lli-hiya** [docker/docker.github.io#6283]
### Problem description

In the doc: https://github.com/docker/docker.github.io/blob/master/registry/recipes/mirror.md, it mentions that the registry can ONLY mirror docker hub, but NOT any private registry. However, this doesn't seem to be the case from my testing.

Our company has a private jfrog registry and after I provide username and password like this:
 ```proxy:
  remoteurl: https://<xxx>.jfrog.io
  username: [username]
  password: [password]
```
it just works perfectly as a pull-through cache. I confirmed that no other credential is overriding this configuration because if I provide a wrong one there, if can no longer pull artifact from our private registry.

Is the documentation wrong?

### Project version(s) affected

Docker:
```$ docker version
Client:
 Version:	18.03.0-ce-rc4
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	fbedb97
 Built:	Thu Mar 15 07:33:28 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce-rc4
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	fbedb97
  Built:	Thu Mar 15 07:42:29 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

Command I run this deploy this registry:

```
docker run -d --restart=always -p 5000:5000 --name registry-mirror -v \`pwd\`/config.yml:/etc/docker/registry/config.yml registry:2
```

Config.yml:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: <aaa>
  username: <bbb>  
  password: <ccc>
```
