### ISSUE TITLE
env_file bad documentation

### ISSUE THREAD

**Issue by reggermont** [docker/docker.github.io#6301]
### Problem description

Hi,
After looking for calling an .env file in a subfolder, I found that it is not possible as the .env file needs to be in the same directory as docker-compose.yml, as confirmed here : https://github.com/docker/compose/issues/4782#issuecomment-298743339

One problem : the documentation doesn't say the same

The doc say that's possible to call an .env file located in `- /opt/secrets.env`. I tried relative and absolute path : both doesn't work. 

### Problem location

Here : https://docs.docker.com/compose/compose-file/#env_file

### Suggestions for a fix

Remove that line : `- /opt/secrets.env` in first example

**Comment by thaJeztah** [comment]
a `.env` file and the `env_file` directive are different things, perhaps that’s where the confusion is? https://github.com/docker/compose/issues/4782#comment-298743339

**Comment by reggermont** [comment]
As shin says : `The env_file directive in your service doesn't change that`
So that's why I think that's an error in the doc.

Also I tried : 
   - `env_file: ./app/.env`
   - `env_file: /home/ME/workspace/MYPROJECT/app/.env`

With this config : 
docker-compose.yml :
```yml 
version: '3.6'

services:

  web:
    container_name: web
    build: docker/web
    env_file: ./app/.env
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./app:/var/www/html
```

./app/.env : 
```yml
APP_PORT=8080
```
