### ISSUE TITLE
IAM PolicyDocument requirements

### ISSUE THREAD

**Issue by nickbreen** [docker/docker.github.io#6728]
File: [docker-for-aws/persistent-data-volumes.md](https://docs.docker.com/docker-for-aws/persistent-data-volumes/)

This page would benefit from a succinct IAM policy document specification for the minimum actions required to support EFS and EBS backed volumes.

[This page](https://docs.docker.com/docker-for-aws/iam-permissions/) is too broad, and there is no way to easily extract the cloudstor relevant policy fragments.

I have tried what appears to be the minimal required actions. See this CloudFormation template fragment:

```yaml
        PolicyDocument:
          Version: '2012-10-17'
          Statement: 
          - Effect: Allow
            Action:
            - ec2:DescribeVolumes
            - ec2:DescribeSnapshots
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - ec2:AttachVolume
            - ec2:DetachVolume
            Resource:
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:instance/*
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:volume/*
          - Effect: Allow
            Action:
            - ec2:CreateVolume
            - ec2:DeleteVolume
            - ec2:CreateTags
            - ec2:DeleteTags
            Resource:
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:volume/*
          - Effect: Allow
            Action:
            - ec2:CreateSnapshot
            Resource:
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:volume/*
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:snapshot/* 
          - Effect: Allow
            Action:
            - ec2:CreateTags
            - ec2:DeleteTags
            - ec2:DeleteSnapshot
            - ec2:ModifySnapshotAttribute
            Resource:
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:snapshot/* 
```

**Comment by nickbreen** [comment]
[Supported Resource-Level Permissions](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/ec2-api-permissions.html#volume)

**Comment by nickbreen** [comment]
This appears to be enough, though I am have not reduced the `ec2:Describe*` privileges any further.

```yaml
        PolicyDocument:
          Version: '2012-10-17'
          Statement: 
          - Effect: Allow
            Action:
            - ec2:DescribeAvailabilityZones
            - ec2:DescribeInstanceAttribute
            - ec2:DescribeInstances
            - ec2:DescribeVolumes
            - ec2:DescribeVolumeAttribute
            - ec2:DescribeVolumesModifications
            - ec2:DescribeVolumeStatus
            - ec2:Describe*
            - ec2:ModifyVolume
            - ec2:ModifyVolumeAttribute
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - ec2:AttachVolume
            - ec2:DetachVolume
            - ec2:*
            Resource:
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:instance/*
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:volume/*
          - Effect: Allow
            Action:
            - ec2:CreateVolume
            - ec2:DeleteVolume
            Resource:
            - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:volume/*
```
