### ISSUE TITLE
Feedback for: compose/compose-file.md

### ISSUE THREAD

**Issue by thechane** [docker/docker.github.io#686]
File: [compose/compose-file.md](https://docs.docker.com/compose/compose-file/)

Is there a doc in the works for version 3 of the compose file ref used in 1.13RC1 'docker deploy --compose-file=blah.yml'? It's hard to test the RC without knowing if my syntax is good.

**Comment by londoncalling** [comment]
@dnephin @nathanleclaire can you jump in here? We do have https://github.com/docker/docker.github.io/tree/vnext-compose/compose, but I don't believe much has changed there.

**Comment by nathanleclaire** [comment]
I have https://github.com/docker/docker/issues/28414 filed as an issue about this.  There's just enough differences to be slightly infuriating, but it's pretty similar to v2.  https://github.com/docker/docker.github.io/pull/672/files?short_path=ec87c9f#diff-ec87c9ff41f9b95df292d0b48170db4f is a start, meanwhile maybe I'll take a look at translating the classic Compose redis-python example.

**Comment by nathanleclaire** [comment]
Alright here's an example.  This is the "swarm-ified" version of the [classic Python-and-Redis compose app](https://docs.docker.com/compose/gettingstarted/).

#### Setup

Place `Dockerfile` in a new directory:

```
FROM python:2.7
ADD . /code
WORKDIR /code
RUN pip install -r requirements.txt
CMD python app.py
```

and `app.py`:

```python
from flask import Flask
from redis import Redis

app = Flask(__name__)
redis = Redis(host='redis', port=6379)

@app.route('/')
def hello():
    redis.incr('hits')
    return 'Hello World! I have been seen %s times.' % redis.get('hits')

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True)
```

and `requirements.txt`:

```
flask
redis
```

#### Compose file

The Compose file is pretty similar.  Main difference is that you shouldn't have `build` I think.

```yaml
version: '3'

networks:
  pyweb:
    driver: overlay

services:
  web:
    image: nathanleclaire/pyweb
    ports:
      - "5000:5000"
    networks:
      - pyweb
    volumes:
      - .:/code

  redis:
    image: redis
    networks:
      - pyweb
```

`docker deploy` [automatically converts `volumes` key to swarm mode service `--mount`s](https://github.com/docker/docker/blob/1f09d68a6e98b8b20ff4e877835bc798cfdb0100/cli/command/stack/deploy.go#L341-L406) so the old standby for bind mounting still works.

#### `docker` commands to deploy the service

Use `docker deploy` to deploy the Compose file and `docker stack` to manage the created "stacks".

```console
$ docker deploy --compose-file docker-compose.yml pyweb
Creating network pyweb_pyweb
Creating network pyweb_default
Creating service pyweb_redis
Creating service pyweb_web

$ curl localhost:5000; echo
Hello World! I have been seen 1 times.

$ docker service ls
ID            NAME         MODE        REPLICAS  IMAGE
9qzad1wj88p8  pyweb_redis  replicated  1/1       redis:latest
xrabnouskr3t  pyweb_web    replicated  1/1       nathanleclaire/pyweb

$ docker stack rm pyweb
Removing service pyweb_redis
Removing service pyweb_web
Removing network pyweb_pyweb
Removing network pyweb_default
```

that's the basic gist.  you can see available "schemas" for the Compose V3 keys [here](https://github.com/docker/docker/blob/master/vendor/github.com/aanand/compose-file/types/types.go), including [previously supported but (for now) unsupported ones](https://github.com/docker/docker/blob/master/vendor/github.com/aanand/compose-file/types/types.go#L7-L28).

**Comment by nathanleclaire** [comment]
good times looks like you can set service properties such as `replicas` in a deploy key.

e.g.:

```
services:
  web:
    image: nathanleclaire/pyweb
    deploy:
      replicas: 3
    ports:
      - "5000:5000"
    networks:
      - pyweb
    volumes:
      - .:/code
```

lots of these around, e.g., [UlimitsConfig](https://github.com/docker/docker/blob/master/vendor/github.com/aanand/compose-file/types/types.go#L105) (I'm assuming meant to be unmarshalled from `ulimits_config`), not sure how many are supported first class, but if you read the schema types in that linked file, you can work your way backwards how to translate swarm settings into the file version.
