### ISSUE TITLE
default values for environment variables?

### ISSUE THREAD

**Issue by waltertross** [docker/docker.github.io#6914]
File: [compose/environment-variables.md](https://docs.docker.com/compose/environment-variables/)
How to declare default values for environment values substitution in situations where the .env file cannot be used?

**Comment by joaofnfernandes** [comment]
If I understand your question correctly, you can use shell parameter substitution.

Your compose file would look like:
```
services:
  lb:
    image: nginx:latest
    environment:
      PASSWORD: "${PASS:-secret}"
```
In the container, set `$PASSWORD` with the value of `$PASS` or default to `secret`. Then you could use:
```
PASS=super-secret docker-compose -f docker-compose-2.yml up
```

Please consider filing a pull request to improve the docs 🙏

**Comment by worp1900** [comment]
I reckon this can be closed as it's fairly well documented here:
https://docs.docker.com/compose/compose-file/#variable-substitution

as referenced in @waltertross documentation:

> For more information, see the Variable substitution section in the Compose file reference.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by JeffreyCA** [comment]
To be exact, it should be:

```
version: '3.1'

services:
  lb:
    image: nginx:latest
    environment:
      - PASSWORD="${PASS:-secret}"
```

Note the added dash and an equal sign instead of a colon.

**Comment by bendavis78** [comment]
@worp1900:

> I reckon this can be closed as it's fairly well documented here:
> https://docs.docker.com/compose/compose-file/#variable-substitution

This page no longer has documentation about variable substitution. Is there an updated link?

**Comment by agrml** [comment]
There's no info about "docker compose default environment variable value" found by google in the documentation. Only this issue is found. Since it's beyond basic bash knowledges, please place it to the compose file docs.

**Comment by kid4git** [comment]
Docs seem to have been restructured by compose file version. This link works:
https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution

**Comment by belegnar** [comment]
```
x-defaults: &defaults
  environment:
    - VAR=value

services:
  service1:
    <<: *defaults
  service2:
    <<: *defaults

```
