### ISSUE TITLE
Issues with Compose file

### ISSUE THREAD

**Issue by arueth** [docker/docker.github.io#7393]
File: [ee/ucp/kubernetes/deploy-with-compose.md](https://docs.docker.com/ee/ucp/kubernetes/deploy-with-compose/)

A partner was running into issues going through this exercise, the following are causing issues:
```yaml
    ports:
     - "80:80"
```
**should be:**
```yaml
    ports:
     - "80"
```

also, the current resource limits cause the pods to continuously crash with OOM errors
```yaml
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 16M
```
**should be:**
```yaml
      resources:
        limits:
          memory: 24M
        reservations:
          memory: 24M
```

This was confirmed and tested on:
Engine: 17.06.2-ee-16
UCP: 3.0.5
DTR 2.5.5
