### ISSUE TITLE
[Get started] part4 should visit to the port 4000 not 80

### ISSUE THREAD

**Issue by LittleYenMin** [docker/docker.github.io#8060]
In [part3](part3.md) set the docker-compose.yml port mapping `4000:80`
but in the ended of part4 just access the `<myvm1 IP address>` to visit the demo page, it won't work should be changed to `<vm1 address:4000>` if people follow the whole tutorial. 

![](https://i.imgur.com/WMGWIk8.png)

docker-compose.yml
```
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: fkym08/demo-friendhello:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
```
