### ISSUE TITLE
docker-compose.yml issue

### ISSUE THREAD

**Issue by KiteBoarder** [docker/docker.github.io#8736]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

with the current docker-compose.yml file, getting this error when running `docker-compose up`: 
```
Creating network "composetest_default" with the default driver
Creating composetest_redis_1 ...
Creating composetest_web_1   ... error

Creating composetest_redis_1 ... done
ind for 0.0.0.0:5000 failed: port is already allocated

```
In order to fix the issue I changed this: - "5000:5000" -> - 5000

For reference: 
Current docker-compose.yml file in the doc: 
```
version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
```

New docker-compose.yml: 

```
version: '3'
services:
  web:
    build: .
    ports:
     - 5000
  redis:
    image: "redis:alpine"
```
