### ISSUE TITLE
Docker Get Started part 3 is out of date 

### ISSUE THREAD

**Issue by galtay** [docker/docker.github.io#8762]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)

The example `docker-compose.yml` file in part 3 of the getting started guide,
https://docs.docker.com/get-started/part3/
```
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: username/repo:tag
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
```

produces a warning about the `deploy` section being ignored when I run `docker-compose config`

```
WARNING: Some services (web) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
```

Docker version 18.09.5, build e8ff056
docker-compose version 1.21.0, build unknown

seems like this breaks the tutorial to me?
