### ISSUE TITLE
Cluster docs are incorrect for providing a subscription

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#9412]
File: [cluster/cluster-file.md](https://docs.docker.com/cluster/cluster-file/)

From reading the docs under https://docs.docker.com/cluster/cluster-file/#cluster, I would expect the syntax to be:
```
cluster:
  subscription: sub-<id>
  license: /path/to/docker_subscription.lic
```
but that doesn't work...it is:
```
cluster:
  subscription:
    id: sub-<id>
    license: /path/to/docker_subscription.lic
```

There appears to be a missing section of all of the values under `subscription`.  I am not sure if there is more than `id` and `license`.
