### ISSUE TITLE
Example Wordpress docker-compose file does not persist content

### ISSUE THREAD

**Issue by jyn514** [docker/docker.github.io#9826]
File: [compose/wordpress.md](https://docs.docker.com/compose/wordpress/)

There is no `volume` entry under `wordpress`, so all data in `/var/www/html/wp-content` will be discarded when you run `docker-compose down`. This is almost certainly not the intended behavior.

The fix is to add this to the compose file:

```
services:
  wordpress:
    volumes:
       - wp_content:/var/www/html/wp-content
volumes:
    wp_content: {}
```
